version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuario_db
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_gimnasio:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  servicio-autenticacion:
    build: ./servicio-autenticacion
    container_name: servicio-autenticacion
    ports:
      - "8081:8081"
    depends_on:
      - db
      - servidor-eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/usuario_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  servicio-membresias:
    build: ./servicio-membresias
    container_name: servicio-membresias
    ports:
      - "8083:8083"
    depends_on:
      - db
      - servidor-eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/usuario_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  servicio-socios:
    build: ./servicio-socios
    container_name: servicio-socios
    ports:
      - "8082:8082"
    depends_on:
      - db
      - servidor-eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/usuario_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  
  servidor-eureka:
    build: ./servidor-eureka
    container_name: servidor-eureka
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8084:8084"
    depends_on:
      - servidor-eureka

volumes:
  db_gimnasio:
    driver: local
